README.md
As in the [IIT's AMI lab](https://ami.iit.it/) use conda/mamba to provide binaries for the libraries contained in the robotology-superbuild (see https://github.com/robotology/robotology-superbuild/blob/master/doc/conda-forge.md), it is convenient to have instruction on how to install adam in a conda environment so that people that use ADAM in Linux or macOS along with robotology libraries. I tested these instructions successfully on conda in Ubuntu 20.04 .
=> Add installation instructions with conda

setup.cfg, tests/test_Jax_computations.py, tests/test_NumPy_computations.py
I've bumped the NumPy version to 1.20 since [NumPy Typing](https://numpy.org/devdocs/reference/typing.html) requires NumPy >= 1.20. 
I'm using this PR also to extend a bit the `setup.cfg` and to remove 2 useless prints spotted in the tests.
Fixes #7
=> Fix numpy typing dep

README.md
If we do not pass this command for the conda packages that do not install correctly the pip metadata, the `pip install .`  command will install again the packages from `PyPI`. 
For example, this will happen for casadi until https://github.com/conda-forge/casadi-feedstock/pull/59 is merged.
=> Specify --no-deps in pip install via conda

README.md, setup.cfg, src/adam/__init__.py, src/adam/casadi/__init__.py, src/adam/jax/__init__.py, src/adam/numpy/__init__.py, src/adam/pytorch/__init__.py, tests/test_CasADi_computations.py, tests/test_Jax_computations.py, tests/test_NumPy_computations.py, tests/test_pytorch_computations.py
I want to update the installation procedure for pruning dependencies that the user might not need in this PR.
For example, the installation would require `PyTorch` even if the user just needs the `CasAdi` interface.
Now the installation would need:
- jax interface:
```bash
pip install .[jax]
```
- casadi interface:
```bash
pip install .[casadi]
```
- pytorch interface:
```bash
pip install .[pytorch]
```
or, if the user does not want to clone the repo:
```bash
pip install adam[selected-interface]@git+https://github.com/ami-iit/ADAM
```
I took also the occasion to change the import syntax.
Before:
```python
from adam.casadi.computations import KinDynComputations
```
After:
```python
from adam.casadi import KinDynComputations
```
The import syntax used before is still working, so the old …
=> Split deps

src/adam/core/rbd_algorithms.py, src/adam/core/urdf_tree.py
In methods like `forward_kinematics` or `jacobian`, we need to access the kinematic tree that goes from the base frame to the end-effector. To get this kinematic chain I use the method `get_chain` (from `urdf_parser_py`), which returns the sequence of the kinematic tree as **[...-link-joint-link-joint-...]** 
Sometimes a link and a joint may have the same name. 
Before I was just checking that an element in the chain is in the joints list, supposing that links and joints could not have the same name. For example, if a joint and a link are named `right_elbow`, the check would return that both the elements are in the joints list. 
To solve this issue I'm allowing the method `get_chain` to return only the joints in the chain.
Changing:
```python
chain = …
```
=> Fix get chain

README.md
`gym-ignition-models`  is just meant to be a repo to be used with `gym-ignition`. The official reference for iCub models, that contains all up-to-date existing iCub models is https://github.com/robotology/icub-models, that thanks to @GiulioRomualdi has a Python interface and is available in both conda-forge and PyPI. See https://github.com/robotology/gym-ignition-models/issues/19 for a related discussion.
=> Avoid gym_ignition_models references in README

src/adam/core/rbd_algorithms.py, src/adam/core/spatial_math.py
This PR adds prismatic joints manipulations. Basically I copy-pasted the modification @CarlottaSartore did in a previous pr.
Since we now support 3 different types of joint it might be worth to generalize the joint interface, since the code contains some duplicates. I'll do it (maybe in a separate PR).
I need a urdf of a robot with prismatic joints to test the modifications.
Fixes #28
=> Add prismatic joints

tests/test_CasADi_computations.py, tests/test_Jax_computations.py, tests/test_NumPy_computations.py, tests/test_pytorch_computations.py
This PR fixes the non-deterministic test failure discussed in https://github.com/conda-forge/staged-recipes/pull/21894#issuecomment-1535488061 and https://github.com/ami-iit/ADAM/pull/38 .
The source of the non-determinism was the use of non-initialized memory, as a `idyntree.bindings.Twist` object was created, but never initialized to zero. In most of the cases their actual value was zero, but sometime its value was actually something else, resulting in a test failure. See the following code snippet for an example:
~~~
>>> import idyntree
>>> a = idyntree.bindings.Twist()
>>> a.toString()
'4.64577e-310 0 6.91004e-310  6.91004e-310 0 2.07508e-322 \n'
>>> a = idyntree.bindings.Twist.Zero()
>>> a.toString()
'0 0 0  0 0 0 \n'
~~~
=> Fix non-deterministic test failure in test_gravity_term 

src/adam/pytorch/torch_like.py, tests/test_CasADi_computations.py, tests/test_Jax_computations.py, tests/test_NumPy_computations.py, tests/test_pytorch_computations.py
This PR hopefully fixes "random" failing tests with Jax and Pytorch. 
See:
- https://pytorch.org/docs/stable/notes/numerical_accuracy.html
- https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision
=> Set float64 

src/adam/model/std_factories/std_link.py
Sometimes in the `.urdf`, a link can contain the `inertial` field (in such a case, we call it `link`, opposite to `frame`, which doesn't have `inertial`) without the origin, e.g.:
```xml
<inertial>
<mass value="0.06"/>
<inertia ixx="1.6854e-05" ixy="0.0" ixz="0.0" iyy="1.6854e-05" iyz="0.0" izz="1.6854e-05"/>
</inertial>
```
In this case, an error arises when `StdLink.spatial_inertial()` or `StdLink.homogeneus()` since `link.inertial.origin` is `None`.
This PR should fix this issue by assigning `link.inertial.origin.xyz = [0,0,0]` and `link.inertial.origin.rpy = [0,0,0]`.
@traversaro do you think that this case can be managed in this way?
=> Set inertial origin to zero when is none in the urdf

setup.cfg
This PR addresses #46.
Since `python3.7` is reaching its EOL (https://www.python.org/downloads/release/python-370/) we might be forced in the future to move to a higher python version.
=> Change python3.8 dep to 3.7

.github/workflows/conda-forge-tests.yml, ci_env_win.yml
Fix https://github.com/ami-iit/ADAM/issues/52 . The downside of this is that we are duplicating dependencies on Windows and Linux/macOS, but at least in this way we do not need to hardcode the Python version used.
=> Use a different ci environment on Windows

src/adam/casadi/computations.py, src/adam/jax/computations.py, src/adam/model/model.py, src/adam/numpy/computations.py, src/adam/pytorch/computations.py
With this PR I want to add the possibility of not passing a list of actuated joints to the model constructor. 
In this case, all the joints that are not fixed are considered actuated joints, e.g.
```python
from adam.casadi import KinDynComputations
... 
comp = KinDynComputations(model_path)
...
```
I also added a check that verifies if all the joints passed as an argument of `KinDynComputations` are in the robot.
=> Add possibility to add empty list of actuated joints

README.md
This PR homologates the repo name to the package one, changing the name from **ADAM** to **adam**.
Fixes #54.
=> Update README.md changing the capitalization (ADAM -> adam)

src/adam/parametric/pytorch/computations_parametric.py, src/adam/pytorch/computations.py, src/adam/pytorch/torch_like.py, tests/body_fixed/test_pytorch_body_fixed.py, tests/mixed/test_pytorch_mixed.py, tests/parametric/test_pytorch_computations_parametric.py
The aim of this PR is to update the Pytorch interface and habilitate its use in deep learning context (i.e. use differentiability). Uniforming to `float64`.
=> Update pytorch interface

src/adam/core/spatial_math.py
With @YuchuanLu we discovered this bug preventing computations for prismatic joints. 
The sum is not defined for a `list` and an `array_like`, so I wrapped the `rpy` (that was in a list) in an array. 
I might come back later for a more smart handling.
=> Fix homogeneous transform computation for prismatic joints

.gitignore, ci_env.yml, ci_env_win.yml, setup.cfg, src/adam/core/spatial_math.py, src/adam/model/abc_factories.py, src/adam/model/conversions/__init__.py, src/adam/model/conversions/idyntree.py, src/adam/model/model.py, src/adam/model/std_factories/std_link.py, src/adam/model/tree.py, src/adam/parametric/casadi/computations_parametric.py, src/adam/parametric/jax/computations_parametric.py, src/adam/parametric/model/__init__.py, src/adam/parametric/model/parametric_factories/parametric_joint.py, src/adam/parametric/model/parametric_factories/parametric_link.py, src/adam/parametric/model/parametric_factories/parametric_model.py, src/adam/parametric/numpy/computations_parametric.py, src/adam/parametric/pytorch/computations_parametric.py, tests/conversions/test_idyntree.py, tests/conversions/test_idyntree_parametric.py
Fixes #68 
Fixes #69 
Fixes #70 
Fixes #71 
This PR also adds a conversion function from an ``adam`` model to an ``iDynTree`` model
=> Parametric improvements

src/adam/casadi/casadi_like.py, src/adam/casadi/computations.py, src/adam/parametric/casadi/computations_parametric.py
This PR comes after #81. A possible solution is to pass to the `Kindyncomputation` constructor also the desired Casadi data type (`cs.MX` or `cs.SX`). Internally this type is used in the Casadi factory to instantiate SX or MX entities.
=> Refactor Casadi interface in order to accept also MX.

src/adam/model/__init__.py, src/adam/model/abc_factories.py, src/adam/model/std_factories/std_link.py, src/adam/model/std_factories/std_model.py, src/adam/parametric/model/parametric_factories/parametric_link.py
This PR fixes #82. 
The link filtering was done by selecting the links with inertia (and frames without inertia; see https://github.com/ami-iit/adam/pull/83#issuecomment-2157581130).
With this fix, massless links with children are also considered connecting links, and the tree is not broken.
=> Fix link filtering

.github/workflows/tests.yml
This PR updates python to 3.11 for the tests, in order to align the deps with `idyntree 12.3.2`. 
Fixes #87
=> Update python version in tests

ci_env.yml, ci_env_win.yml, setup.cfg, src/adam/casadi/computations.py
Enable common subexpression elimination by default to eliminate redundant computations efficiently. This feature was introduced in [CasADi 3.6](https://github.com/casadi/casadi/releases/tag/3.6.0).
I changed the minimum supported version of Casadi to `v3.6`
=> Enable common subexpression elimination of casadi functions

README.md, src/adam/casadi/casadi_like.py, src/adam/casadi/computations.py, src/adam/parametric/casadi/computations_parametric.py
I did some tests using `casadi.MX`, and I figured out that that MX is not really elastic. For example, a "numeric MX" (an MX filled with numbers) cannot be converted to a DM, while a "numeric SX" can. 
Also, MX and SX cannot be converted to each other.
On the other hand, passing through a `casadi.Function` allows the user to choose the type of the input and have the output of the same type, i.e.
```python
a_sx = cs.SX.sym('a')
b_sx = cs.SX.sym('b')
fun = cs.Function('fun', [a,b], [a+b])
c_sx = fun(a_sx, b_sx)
a_mx = cs.MX.sym('a')
b_mx = cs.MX.sym('b')
c_mx = fun(a_mx, b_mx)
```
For this reason (and also because I've not implemented sufficient tests) I want to revert #84, for now, and just do the computation with `casadi.SX` and exploit the `casadi.Function`.
=> Remove casadi.MX 

README.md
A small update of the readme. Adding some details on jit and vmap of jax functions.
=> Update README.md for Jax usage

README.md, ci_env.yml, setup.cfg, src/adam/pytorch/__init__.py, src/adam/pytorch/computation_batch.py, tests/pytorch_batch/test_pytorch_batch.py
This PR exploits the package [jax2torch](https://github.com/lucidrains/jax2torch), based on the [gist](https://gist.github.com/mattjj/e8b51074fed081d765d2f3ff90edf0e9) which explains how to convert `jax` functions in `pytorch` ones, preserving also the gradients. 
This should allow to perform batch computations, e.g.
```python
H_b_batch = torch.tile(torch.tensor(H_b), (n_samples, 1, 1)).requires_grad_()
joints_val_batch = torch.tile(torch.tensor(joints_val), (n_samples, 1)).requires_grad_()
mass_matrix = kindyn.mass_matrix(H_b_batch, joints_val_batch)
mass_matrix.sum().backward()
```
I put this interface in `adam.pytorch` as `KinDynComputionBatch`, even if it using `jax` under the hood.
```python
from adam.pytorch import KinDynComputationsBatch
kindyn = KinDynComputationsBatch(model_path, …
```
=> Allow pytorch batching using jax2torch

.github/workflows/black.yml, .github/workflows/pypi-ci.yml, .github/workflows/tests.yml
CI were failing due to a deprecated version of some GitHub Actions used.
```shell
This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. 
Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
=> Update GitHub Actions and runners OS

.github/workflows/black.yml, .github/workflows/pypi-ci.yml, .github/workflows/tests.yml, examples/mpc-ik.ipynb, src/adam/model/std_factories/std_model.py, tests/parametric/test_CasADi_computations_parametric.py, tests/parametric/test_Jax_computations_parametric.py, tests/parametric/test_NumPy_computations_parametric.py, tests/parametric/test_pytorch_computations_parametric.py
This PR updates the parsing logic for URDF files by bounding the check on file existence to the maximum path length allowed by the OS. Moreover, some changes were made to make the RW operations on files safer and some final linting was performed. 
Closes https://github.com/ami-iit/comodo/issues/21
----
📚 Documentation preview 📚: https://adam-docs--100.org.readthedocs.build/en/100/
=> Update URDF parsing logic and improve R/W operations on files

.github/workflows/pypi-ci.yml
This PR fixes the PyPI deployment on CI. In this way, the workflow will be disabled for the forks of this repository (See failing job on https://github.com/ami-iit/adam/actions/runs/11667895168/job/32486274590?pr=103)
----
📚 Documentation preview 📚: https://adam-docs--105.org.readthedocs.build/en/105/
=> Fix PyPI deployment on CI

src/adam/model/std_factories/std_model.py
This pull request includes a small change to the `get_xml_string` function in the `src/adam/model/std_factories/std_model.py` file. The change simplifies the condition for converting a string to a `pathlib.Path` object by removing the redundant check for the existence of the path. In this way, an error will be raised when a non-existing string-type path is passed
=> Raise error if a non-existing string-type path is passed

.github/workflows/pypi-ci.yml
The pypi action fails with:
```
Unable to download artifact(s): Artifact not found for name: dist
Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```
This PR wants to solve this (but I'm not sure it works).
I should also change the logic triggering the `test_PyPi`, ideally with and additional manual trigger.
See: https://github.com/actions/download-artifact?tab=readme-ov-file#download-multiple-filtered-artifacts-to-the-same-directory
----
📚 Documentation preview 📚: https://adam-docs--107.org.readthedocs.build/en/107/
=> Fix PyPi test and upload action

README.md
After https://github.com/conda-forge/adam-robotics-feedstock/pull/12 .
----
📚 Documentation preview 📚: https://adam-docs--108.org.readthedocs.build/en/108/
=> Update installation instruction when installing conda packages

.github/workflows/pypi-ci.yml, .github/workflows/tests.yml
I changed the action to publish to PyPI and TestPypi.
Following: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
----
📚 Documentation preview 📚: https://adam-docs--110.org.readthedocs.build/en/110/
=> Change GitHub Actions workflow for PyPi

README.md
The example used `cs.SX.eye(4)` but never imported casadi as `cs` .
----
📚 Documentation preview 📚: https://adam-docs--113.org.readthedocs.build/en/113/
=> Fix casadi example in the README

src/adam/casadi/computations.py, src/adam/core/rbd_algorithms.py, src/adam/jax/computations.py, src/adam/numpy/computations.py, src/adam/parametric/casadi/computations_parametric.py, src/adam/parametric/jax/computations_parametric.py, src/adam/parametric/numpy/computations_parametric.py, src/adam/parametric/pytorch/computations_parametric.py, src/adam/pytorch/computation_batch.py, src/adam/pytorch/computations.py
@GiulioRomualdi spotted some wrong arguments in the pytorch interface. 
Fixed `joint_position` to `joint_postions` as in the other functions.
Took the occasion also to fix other wrong comments.
Changing also the `raise DeprecationWarning` for the use of the `root_link` introduced in #114 to a more mild `warning.warn()`. 
----
📚 Documentation preview 📚: https://adam-docs--116.org.readthedocs.build/en/116/
=> Fix comments and function arguments

src/adam/casadi/computations.py, src/adam/core/rbd_algorithms.py, src/adam/jax/computations.py, src/adam/numpy/computations.py, src/adam/parametric/casadi/computations_parametric.py, src/adam/parametric/jax/computations_parametric.py, src/adam/parametric/numpy/computations_parametric.py, src/adam/parametric/pytorch/computations_parametric.py, src/adam/pytorch/computation_batch.py, src/adam/pytorch/computations.py, tests/conftest.py, tests/test_casadi.py, tests/test_idyntree_conversion.py, tests/test_jax.py, tests/test_numpy.py, tests/test_pytorch.py, tests/test_pytorch_batch.py
This PR adds the method to compute the Center of Mass jacobian.
----
📚 Documentation preview 📚: https://adam-docs--117.org.readthedocs.build/en/117/
=> Add CoM Jacobian method

src/adam/parametric/pytorch/computations_parametric.py, src/adam/pytorch/computation_batch.py, src/adam/pytorch/computations.py, src/adam/pytorch/torch_like.py
This pull request includes several changes to improve the handling of data types and default values in the `adam` package. The most important changes include updates to the initialization methods in two computation files and modifications to the `TorchLike` class to use the default tensor type.
Improvements to initialization methods:
* [`src/adam/parametric/pytorch/computations_parametric.py`](diffhunk://#diff-bfca0bc7dfb92ba51b552a3373e9bed6b76e4af02948d8abe8dac203b68d5cc5L26-R26): Simplified the `gravity` parameter in the `__init__` method by removing the explicit `dtype` specification.
* [`src/adam/pytorch/computations.py`](diffhunk://#diff-af8c79f945c2f1f72c9c251ed744891d6a26b2043307c6394d0e8d75d9b79eb4L23-R23): Simplified the `gravity` parameter in the `__init__` method by removing …
=> Refactor gravity parameter initialization and update post-init array conversion to use default dtype

src/adam/model/std_factories/std_model.py
This pull request includes a change to the `get_xml_string` function in the `src/adam/model/std_factories/std_model.py` file. The change simplifies the path length check and ensures that paths are resolved correctly.
Key change:
* Removed the extraction of the maximum path length for the current OS and modified the path check to always resolve the path if it is not an XML string.
----
📚 Documentation preview 📚: https://adam-docs--125.org.readthedocs.build/en/125/
=> Refactor path handling in `get_xml_string` to simplify OS-specific checks

README.md, ci_env.yml, ci_env_win.yml, pyproject.toml, src/adam/casadi/__init__.py, src/adam/casadi/inverse_kinematics.py
This pull request introduces an inverse kinematics module to the `adam.casadi` package. The changes include the addition of a new `InverseKinematics` class, which provides functionality for solving various inverse kinematics problems, such as position, orientation, and pose targets, as well as constraints between frames. The most important changes are detailed below.
* **`src/adam/casadi/inverse_kinematics.py`:** Added the `InverseKinematics` class, which includes methods for defining targets (position, orientation, pose), updating targets, adding constraints (e.g., ball, hinge, fixed), setting initial guesses, solving the optimization problem, and retrieving the solution. This class leverages CasADi for optimization and symbolic computation.
* **`src/adam/casadi/__init__.py`:** Imported …
=> Add InverseKinematics class

ci_env.yml, pyproject.toml, src/adam/casadi/inverse_kinematics.py
This PR provides a temporary fix for the recent jax update from version 0.6.0 to 0.7.0.
See #132 and #131. 
For now, I'm fixing the JAX version in the dependencies to the last working version. 
I'll fix the general issue hopefully soon.
---
This pull request updates the way the `jax` dependency is specified in both the `ci_env.yml` and `pyproject.toml` files. The main change is to pin the version of `jax` to `0.6.0` instead of allowing any version, which helps ensure consistent environments and reduces the risk of incompatibility issues.
Dependency version pinning:
* Updated the `ci_env.yml` file to specify `jax==0.6.0` instead of an unpinned version for more predictable CI builds.
* Modified the `pyproject.toml` file to pin `jax` to version `0.6.0` in both the `jax` optional dependency …
=> Fix jax version to 0.6.0 in dependencies [TEMPORARY FIX]

.github/workflows/pypi-ci.yml, pyproject.toml
This pull request updates the Python packaging and publishing workflow, aligning it with https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
**CI/CD Workflow Improvements:**
* Simplified and restructured the `.github/workflows/pypi-ci.yml` workflow triggers, ensuring builds run on release, pull request, and workflow dispatch events, and made event types more explicit.
* Refactored job dependencies and artifact naming: standardized the artifact name to `dist`, set explicit job dependencies using `needs`, and improved artifact download/upload steps for consistency across jobs.
* Removed the `github-release` job that signed distributions with Sigstore and uploaded them to GitHub Releases, focusing the workflow solely on …
=> Fix pypi-ci workflow
